feat(server) Tagging system
immich-app/immich pull request #1046
Opened 2022-12-02 20:21 UTC by alextran1502

This PR implements tagging system for Immich

2022-12-03 14:32 UTC, zoodyy commented on server/apps/immich/src/api-v1/asset/asset-repository.ts
> +        const tag = await this.tagRepository.findOne({ where: { id: tagId } });
a findAll for an array of tagIds should be more performant and more elegant because it only returns those tags that are found (and not possibly null)

2022-12-05 14:07 UTC, bo0tzz requested changes
Do I understand correctly that this PR implements the new tags system serverside, but for now everything still uses the old tags column in the SmartInfo table? I assume there'll then be a followup PR to change over the background jobs, clients, and to migrate the old tags from SmartInfo?

PR looks good, as usual just a few small nits.

2022-12-05 14:28 UTC, jrasm91 commented on server/apps/immich/src/api-v1/asset/asset-repository.ts
> +
If I'm not mistaken, all of our yeah functionality is user scored, right? IMO, all the queries should include the user id, which would address this problem.

2022-12-05 15:14 UTC, alextran1502 commented
> I assume there'll then be a followup PR to change over the background jobs, clients, and to migrate the old tags from SmartInfo?

Correct, that will be is my upcoming PRs

2022-12-05 15:18 UTC, bo0tzz commented on server/apps/immich/src/api-v1/asset/asset-repository.ts
> +
Agree. I think that would also remove the need for explicit `checkTagOwnership` checks.

2022-12-05 15:54 UTC, jrasm91 commented on NOTES.md
> +# Tagging system
Does this file need to be committed? Are we going to start documenting "notes" here? Should we maybe just add something like this to the documentation site instead?

2022-12-05 17:17 UTC, bo0tzz approved these changes

2022-12-05 17:21 UTC, jrasm91 approved these changes
Few semantic things about modules :stuck_out_tongue: otherwise looks good!

2022-12-05 17:21 UTC, jrasm91 commented on server/apps/immich/src/api-v1/tag/tag.module.ts
> +  exports: [TAG_REPOSITORY_PROVIDER, TypeOrmModule],
Shouldn't need to export `TypeOrmModule` here either.

2022-12-05 17:21 UTC, jrasm91 commented on server/apps/immich/src/api-v1/tag/tag.repository.ts
> +    private assetRepository: Repository<AssetEntity>,
Are these repositories used here?

2022-12-05 17:21 UTC, jrasm91 commented on server/apps/immich/src/api-v1/user/user.module.ts
> +  exports: [USER_REPOSITORY_PROVIDER, TypeOrmModule],
This isn't needed here either.

2022-12-05 17:21 UTC, jrasm91 commented on server/apps/immich/src/api-v1/asset/asset.module.ts
> +  exports: [ASSET_REPOSITORY_PROVIDER, TypeOrmModule],
Should not need to export `TypeOrmModule`

2022-12-05 17:56 UTC, merged