Document video transcode policy
immich-app/immich pull request #13388
Opened 2024-10-12 12:18 UTC by kevincox

I was trying to figure out what this means myself and ended up reading the code to determine the requirements. I figured I would document this to help future readers.

Let me know if there is a better place for this documentation (such as https://immich.app/docs/administration/system-settings/#video-transcoding-settings). I will happily send a PR there instead or in addition to this one.

2024-10-12 13:09 UTC, crash123 commented on server/src/enum.ts
> +  // Videos are transcoded if they don't mee the format requirements or are too high resolution.
meet

2024-10-12 13:09 UTC, crash123 commented on server/src/enum.ts
> +  // Videos are transcoded if they don't mee the format requirements or the video bitrate is over `maxBitrate`
meet

2024-10-12 13:09 UTC, crash123 commented on server/src/enum.ts
> +  // Videos are only transcoded if they don't meed the format requirements.
meet

2024-10-12 13:10 UTC, crash123 commented on server/src/enum.ts
> +  // - The audia codec is not in `acceptedAudioCodecs`
audio

2024-10-12 13:39 UTC, mmomjian commented
I feel like this should be written up in the Immich docs, not as comments in a file.

2024-10-12 16:48 UTC, danieldietzler requested changes, later dismissed
I agree, this shouldn't be a comment in the code as people who read the code typically know how to figure it out themselves anyways. If anything, this should help people figuring out the correct setting in the GUI

2024-10-12 16:53 UTC, mertalev commented
It can go in the transcode policy description in a more condensed form.

2024-10-12 16:54 UTC, kevincox commented
Can you clarify where you would like to see this?

2024-10-12 16:59 UTC, kevincox commented
> the use of "optimal" as the resolution-based policy has always bothered me. Calling it "resolution" would be easier to understand.

A nice improvement would be to separate our resolution and bitrate into flags rather than presets. Right now you can pick either but not both, example (I would like to transcode if either resolution or bitrate is over the preference). Or maybe it would be better to specify this similar to video formats where there is allowed and the target when transcoding specified separately. So you would have transcode policy Always, Required, Never then have targetBitrate, maxBitrate and targetResolution, maxResolution. But that is a bigger change than just documenting the current state.

2024-10-12 16:59 UTC, mertalev commented
In the video transcoding settings in the admin UI.

2024-10-12 17:05 UTC, kevincox commented
Hmm, the problem with putting it there is that if you are setting the values from the config file you can't actually see the descriptions of individual settings.

[Screencast from 2024-10-12 13-03-32.webm](https://github.com/user-attachments/assets/7c87563c-f68d-47bd-b4d7-bca54762925e)

It also doesn't list the settings "keyword". Maybe we need some sort of documentation that can appear both in the UI and in some place for people using the config file?

2024-10-12 17:06 UTC, mertalev commented
I agree setting them as toggles would be nice to mix and match. It'd implicitly document how it works as well, such as having toggles for HDR etc.

2024-10-12 17:28 UTC, mertalev commented
> Hmm, the problem with putting it there is that if you are setting the values from the config file you can't actually see the descriptions of individual settings.
> 
> 
> 
> [Screencast from 2024-10-12 13-03-32.webm](https://github.com/user-attachments/assets/7c87563c-f68d-47bd-b4d7-bca54762925e)
> 
> 
> 
> It also doesn't list the settings "keyword". Maybe we need some sort of documentation that can appear both in the UI and in some place for people using the config file?
> 
> 

Hmm, I guess putting in the docs and linking to it in the admin UI would be best. There'd be more room to explain config file usage that way. It's okay to put it in the section you mentioned in the OP for the scope of this PR, but in the future it'd be nicer to have a separate transcoding page instead.

2024-10-14 13:35 UTC, kevincox commented on docs/docs/administration/system-settings.md
Ok, I've moved the docs to that page. I also expanded a bit to cover most of the Immich-specific settings in there. For now I have left out things that are basically ffmpeg flags.

I used the config file attribute as the heading name, but I'm not sure if this is the best option as it won't make as much sense for people configuring things in the UI. I could use the english names in the headers and mention the config properties in the body instead if that is preferable. I don't know if that would be confusing to people using Immich in other localizations but I AFAICT the docs aren't localized so I don't know if there is a better option.

2024-10-18 12:34 UTC, mertalev commented on docs/docs/administration/system-settings.md
> +In addition to the conditions in `required`, video is also transcoded if the horizontal **and** vertical resolutions are higher than `targetResolution`.
```suggestion
In addition to the conditions in `required`, video is also transcoded if the horizontal **and** vertical dimensions are higher than `targetResolution`.
```

2024-10-18 12:34 UTC, mertalev commented on docs/docs/administration/system-settings.md
You can use the English title for them and put the JSON path in parentheses, clarifying at the start that this is what the parentheses mean.

2024-10-26 12:42 UTC, kevincox commented on docs/docs/administration/system-settings.md
Done.

2024-10-29 05:03 UTC, alextran1502 commented
Thank you for the PR. However, the subtitles in the settings are self-explanatory, and breaking them down in the documentation will cause a mismatch when we change them, creating a maintenance burden. I will close the PR for the reason above.

2024-10-29 09:21 UTC, kevincox commented
The settings UI is one thing but there is currently zero documentation for the config file. I had to read the source to figure it out which I assume is not considered acceptable UX.

2024-10-29 13:01 UTC, alextran1502 commented
@kevincox ah that is fair, sorry I misunderstood the purpose of the PR

2024-10-31 22:26 UTC, kevincox commented on docs/docs/administration/system-settings.md
> +- The video is HDR.
How should I handle this? That change isn't live yet. I can prepare a PR to merge once that goes in or we can add a note to that PR if it doesn't land before this one.

2024-10-31 22:26 UTC, kevincox commented on docs/docs/administration/system-settings.md
> +#### Only videos not in an accepted format (`required`) {#ffmpeg.transcode-required}
I've added that property to the docs in a separate section.

2024-11-01 00:48 UTC, mertalev commented on docs/docs/administration/system-settings.md
> +- The video is HDR.
It's live now :P

2024-11-01 01:36 UTC, kevincox commented on docs/docs/administration/system-settings.md
> +- The video is HDR.
Added the condition.

2024-11-01 02:42 UTC, mertalev reviewed
A few minor nits, otherwise looks good!

2024-11-01 02:42 UTC, mertalev commented on docs/docs/administration/system-settings.md
> +- The video is not in the yuv420p colour space.
```suggestion
- The video is not in the yuv420p pixel format.
```

2024-11-01 02:42 UTC, mertalev commented on docs/docs/administration/system-settings.md
> +If the video asset's container format is not in this list it will be remuxed to MP4 even if no streams need to be transcoded.
```suggestion
If the video asset's container format is not in this list, it will be remuxed to MP4 even if no streams need to be transcoded.
```

2024-11-01 02:42 UTC, mertalev commented on docs/docs/administration/system-settings.md
> +The transcoding policy configures which streams of a video asset will be transcoded. The transcoding decision is made independently for video streams and audio streams. This means that if a video str
```suggestion
The transcoding policy configures which streams of a video asset will be transcoded. The transcoding decision is made independently for video streams and audio streams. This means that if a video stream needs to be transcoded, but an audio stream does not, then the video stream will be transcoded while the audio stream will be copied. If the transcoding policy does not require any stream to be transcoded and does not require the video to be remuxed, then no separate video file will be created.
```
It is actually possible for a video to not be transcoded and simply remuxed.

2024-11-02 04:08 UTC, mertalev approved these changes

2024-12-16 17:20 UTC, merged