feat(server): faster metadata extraction
immich-app/immich pull request #14277
Opened 2024-11-21 07:33 UTC by mertalev

## Description

* Groups async calls where possible rather than doing them sequentially
* Moves some checks to be done synchronously without `await`
* Extracts live photo logic into a private method that metadata extraction runs
* No longer queues live photo job as part of upload pipeline
* Removes redundant `stat` calls, instead relying on exiftool
* Use async hash function to avoid blocking the event loop

Besides being significantly faster, it also makes job progress more intuitive as the number of waiting jobs goes down as one would expect without other jobs being queued in their place.

### Testing

<img width="488" alt="metadata-extraction-rate" src="https://github.com/user-attachments/assets/8423352f-dbc5-4071-a387-30059476f5a3">

The y-axis is jobs/s. The first part is main and the second is this PR. The jump toward the end is when the queueing job finished queueing assets (the job is somewhat intensive with a large table). There is an increase on main as well if you look closely, but it's more subtle. I canceled both when their progress rate stabilized after the queueing job finished.

2024-11-21 12:18 UTC, jrasm91 requested changes
Two parts of a live photo can be uploaded at the same time and won't be linked if their metadata extraction jobs are processed in parallel. That was why it was moved to a separate job in the first place.

2024-11-21 12:22 UTC, jrasm91 commented
It might be sufficient to save the CID value to the database prior to running the link logic post of the job though.

2025-02-27 13:46 UTC, jrasm91 reviewed
This looks pretty good but it has a ton of improvements that would have been better as separate pull requests. Can you separate out all these things? 
- exif tool concurrency control
- exif tool stat call
- live photos job change
- metadata async calls in parallel

2025-02-27 23:16 UTC, mertalev commented
Closing this PR in favor of splitting it into smaller, more focused PRs.

2025-02-27 23:16 UTC, closed without merging