feat: transcode in stats
immich-app/immich pull request #14418
Opened 2024-11-30 22:38 UTC by guyfischman

Adds transcoded videos storage usage to the server stats page, both for users and server total.

Mentioned in https://github.com/immich-app/immich/discussions/14093.

2024-11-30 22:45 UTC, danieldietzler approved these changes
I'm not even sure if we want this tbh. To me this sounds somewhat counterintuitive. When thinking about quota I think about how much data they are allowed to upload

2024-11-30 22:45 UTC, danieldietzler commented on server/src/repositories/user.repository.ts
> +        `ARRAY_AGG(assets.encodedVideoPath) FILTER (WHERE assets.encodedVideoPath IS NOT NULL)`,
I feel like this is gonna be veeeery slow

2024-11-30 22:45 UTC, danieldietzler commented on server/src/services/server.service.spec.ts
> +  });
This is now how you should be doing that. You should be mocking repo methods if you have to

2024-11-30 22:45 UTC, danieldietzler commented on server/src/services/server.service.ts
> +          const stats = fs.statSync(path);
Pretty sure we already have a repo method for that. If we don't, we should add one

2024-11-30 22:45 UTC, danieldietzler requested changes
Clicked the wrong button oof

2024-11-30 22:54 UTC, mertalev requested changes
I'm not fully convinced we need this. There is an elegance to only counting the original files - it aligns with how cloud solutions count usage, is independent from the particular settings of the admin and the immich release, and leads to a more intuitive quota for the user. This PR only changes the visible stats, but this is also confusing since there's a discrepancy between what is actually included in the quota and what is displayed.

Even if we come to an agreement there, the particular approach in this PR is too bolted-on and would need to be designed in a better way that doesn't require scanning the file system and encompasses other generated files like thumbnails.

2024-11-30 22:54 UTC, mertalev commented on server/src/services/server.service.ts
> +          const stats = fs.statSync(path);
This is terribly slow and will scale poorly as the number of videos increases, both in fetching every single path from the DB at once and in `stat`'ing them like this.

2024-11-30 23:06 UTC, guyfischman commented
> I'm not even sure if we want this tbh. To me this sounds somewhat counterintuitive. When thinking about quota I think about how much data they are allowed to upload
> I'm not fully convinced we need this. There is an elegance to only counting the original files - it aligns with how cloud solutions count usage, is independent from the particular settings of the admin and the immich release, and leads to a more intuitive quota for the user. This PR only changes the visible stats, but this is also confusing since there's a discrepancy between what is actually included in the quota and what is displayed.

I agree as regards the user's expectation. My change is only for the admin panel (at least that's how I intended it).

> I feel like this is gonna be veeeery slow
> This is terribly slow and will scale poorly as the number of videos increases, both in fetching every single path from the DB at once and in stat'ing them like this.

I agree, and now don't know why I did it this way to begin with. I think I didn't see the transcoded filesize in the db schema and wanted something that just worked now. I guess a more reasonable solution is to have the transcoding job update the asset table with the new file's size so it can be queried directly.

> Even if we come to an agreement there, the particular approach in this PR is too bolted-on and would need to be designed in a better way that doesn't require scanning the file system and encompasses other generated files like thumbnails.

Happy to include other things like thumbnails, database, and immich code itself tbh. I'd like the admin panel to just show everything immich is using. Transcoding just seemed like the biggest chunk.

2024-12-01 05:56 UTC, mertalev commented
You're right - the file size for transcodes etc. isn't stored anywhere. I think it'd be reasonable to add a file size column in the `asset_files` table and move `encodedVideoPath` from `assets` over to this table. You could change the associated jobs to include file size when updating the DB (sharp's `toFile` provides this info and I believe fluent-ffmpeg does as well, so you shouldn't need separate `stat` calls). Getting this info would then just be a query on `asset_files` without touching the file system.

The only limitation of this is that it won't retroactively count files generated before this change, but I think this is okay as long as it's noted somewhere.

2024-12-11 23:06 UTC, alextran1502 commented
Hello, we have some incoming changes to the database that relate to files in the database. It will be cleaner to use that mechanism to report these stats. Hence, I am closing this PR for now. Sorry, and thank you for the contribution; for future reference, please contact us first on Discord if you plan on opening a larger PR.

2024-12-11 23:06 UTC, closed without merging

2024-12-12 15:45 UTC, guyfischman commented
> Hello, we have some incoming changes to the database that relate to files in the database. It will be cleaner to use that mechanism to report these stats. Hence, I am closing this PR for now. Sorry, and thank you for the contribution; for future reference, please contact us first on Discord if you plan on opening a larger PR.

Thanks - FTR I did contact on discord first :).