feat(server): change clipembedding entity type
immich-app/immich pull request #2091
Opened 2023-03-27 07:32 UTC by michelheusschen

Currently `clipEmbedding` is stored as `numeric(20, 19)`, but I think it's better to convert that to `float8`. According to my tests, Typesense limits floats to 17 significant digits anyway.

With a dataset of 830 assets with 512 clipEmbedding values each (424.960 numbers), I tested converting the numeric type to float4 and float8.
- Converting to float4 meant that 338 out of 424.960 numbers lost some precision
- And converting to float8 saw 0 numbers lose precision

The `numeric(20, 19)` type can only store values between -9.999... and 9.999..., but in my dataset there was a value of `-9.9260091781616210000` which is pretty close to that limit. There are also some reports of `QueryFailedError: numeric field overflow` errors when inserting to the `smart_info` table. There could be a hard limit on the values of clipEmbedding that prevents them from going below -10, but by using a floating point this is no longer a concern.

And as an added bonus the table size shrinked from 5.1MiB to 2.8MiB (830 assets)

2023-03-27 08:33 UTC, fyfrey requested changes
Storing as `float8` (usually called double in most programming languages) makes certainly more sense than `numeric` which is an configurable precision type used to store money values or when performing scientific calculations requiring arbitrary precision.

The CLIP model (and most other models by default) produce normal float values (`float4` in postgres). It makes no sense to store embeddings in any format larger than `float4` - any errors you might see are rounding issues from converting. SO selecting `float4` (32-bit float) is best for the specific model.

However, it might be better if we do following (if possible): Store the output (embeddings) retrieved from the ML model (CLIP) as raw bytes without any conversion in postgres and transfer that to typesense and configure it to interpret the values as required (e.g. 32-bit floats). In case the user selects another mode where e.g. quantization has been applied that uses 16-bit float, just store it as bytes in postgres and give to typesense with the remark to intepret as 16-bit float etc.

2023-03-27 09:36 UTC, michelheusschen commented
> The CLIP model (and most other models by default) produce normal float values (`float4` in postgres). It makes no sense to store embeddings in any format larger than `float4` - any errors you might see are rounding issues from converting. SO selecting `float4` (32-bit float) is best for the specific model.
> 
> However, it might be better if we do following (if possible): Store the output (embeddings) retrieved from the ML model (CLIP) as raw bytes without any conversion in postgres and transfer that to typesense and configure it to interpret the values as required (e.g. 32-bit floats). In case the user selects another mode where e.g. quantization has been applied that uses 16-bit float, just store it as bytes in postgres and give to typesense with the remark to intepret as 16-bit float etc.

I agree that changing the data type to float4 makes most sense, as any small deviation in value is unlikely to impact the search result.

However, the suggestion to store the embeddings as raw bytes doesn't make much sense to me. Typesense only has one [`float` type](https://typesense.org/docs/0.24.0/api/collections.html#field-types) and sending bytes to be interpreted as a float with a certain precision may not be possible. The embeddings are received from ML as JSON, and storing them as raw bytes would add an extra conversion layer on the server that is error-prone, makes it harder to debug, and produces values that aren't human-readable.

2023-03-27 11:36 UTC, jrasm91 approved these changes

2023-03-27 20:19 UTC, fyfrey approved these changes

2023-03-28 05:42 UTC, alextran1502 commented
@jrasm91 Do we need to re-index Typesense after the migration is run?

2023-03-28 06:23 UTC, jrasm91 commented
I don't think so, it should be the same data, just less precise, but the field type is the same in typesense.

2023-03-28 14:53 UTC, merged