Map Feature
immich-app/immich pull request #2292
Opened 2023-04-19 15:55 UTC by EPP100

A map view to display where photos were taken

2023-04-19 16:42 UTC, bo0tzz requested changes
Thanks for the PR! For now, just a few high level thoughts from me.

2023-04-19 16:42 UTC, bo0tzz commented on web/src/lib/components/map-page/photos-map-view.svelte
> +/>
Please install this as an NPM dependency instead of using a CDN.

2023-04-26 22:27 UTC, colin715 commented on server/immich-openapi-specs.json
> +            "description": "Only returns albums that contain the asset\rIgnores the shared parameter\rundefined: get all albums",
FYI, I believe that EPP said on discord that he wouldn't be able to work on this further

2023-04-29 14:15 UTC, bo0tzz commented
Superseded by #2355

2023-04-29 14:15 UTC, closed without merging

2023-04-29 17:53 UTC, jrasm91 commented
Thanks for kick starting this!