Add extended redis & DB port configuration via enviroment variables
immich-app/immich pull request #330
Opened 2022-07-11 11:56 UTC by zoodyy

Add env variables to better support shared redis & db running on the host system or in other containers:

1. Add env variable `DB_PORT` to change the database port.
2. Add env variables `REDIS_PORT`, `REDIS_DBINDEX`, `REDIS_PASSWORD` and `REDIS_SOCKET` to configure connections to use a shared redis instance (optionally via unix sockets)

2022-07-11 12:30 UTC, zackpollard requested changes
Hey, thanks for the PR. I think making the REDIS connection configurable is a great idea, but I would request that for the normal user it is no more options than it is now. Therefore could you please default the all the redis values to what they were previously. Could you also please comment these values out in the .env file so people don't think they need to set them for the normal use case.

2022-07-11 12:50 UTC, zoodyy commented
Hey, thanks for the quick feedback. No defaults were changed in my earlier commits.
I've now changed the the `.env.example` to show which values are optional.

2022-07-11 14:47 UTC, alextran1502 commented on machine-learning/src/config/database.config.ts
> +  port: parseInt(process.env.DB_PORT || '5432'),
Should this be
```
port: parseInt(process.env.DB_PORT || 5432),
```

2022-07-11 14:52 UTC, zackpollard commented
> Hey, thanks for the quick feedback. No defaults were changed in my earlier commits. I've now changed the the `.env.example` to show which values are optional.

Thanks, these changes look good to me now!

2022-07-11 14:52 UTC, zackpollard approved these changes

2022-07-12 00:07 UTC, aruhier commented
Can you also allow using Postgres in SSL through the environment variables?

2022-07-12 07:27 UTC, zoodyy commented
> Can you also allow using Postgres in SSL through the environment variables?

You can specify `PGSSLMODE=require` as env variable (possibly together with `PGSSLCERT`, `PGSSLKEY`, `PGSSLROOTCERT` containing the content of the certificate/key files)

2022-07-13 03:21 UTC, merged