fix(server): strip metadata from thumbnails
immich-app/immich pull request #4438
Opened 2023-10-11 14:52 UTC by uhthomas

#3658 introduced support for thumbnail ICC profiles, but also inadvertently included all thumbnail metadata. It seems this has to be explicitly disabled.

Refs: #4382

2023-10-11 17:07 UTC, mertalev requested changes
I don't think false is a valid argument here for the withMetadata API. The second call also overwrites the first; they can't be stacked like that.

2023-10-11 17:41 UTC, uhthomas commented
> I don't think false is a valid argument here for the withMetadata API. The second call also overwrites the first; they can't be stacked like that.

It is valid, but missing from the TypeScript definition (https://github.com/lovell/sharp/issues/3822).

I think you're right though, and the original change would not behave as expected.

https://github.com/lovell/sharp/blob/eefaa998725cf345227d94b40615e090495c6d09/src/pipeline.cc#L792

I've updated the PR to first create the resized image without metadata, and then a second image with the ICC profile.

2023-10-11 17:45 UTC, mertalev reviewed
I think this looks good, but it needs testing to make sure it handles colors and bit depth correctly.

2023-10-11 17:46 UTC, jrasm91 commented
Can you add to the description how you have tested this? What formats you validated it with, etc.

2023-10-14 20:28 UTC, alextran1502 commented
@etnoy When you have a chance can you help with fixing the e2e test?

2023-10-14 21:50 UTC, etnoy commented
> @etnoy When you have a chance can you help with fixing the e2e test?

should be done now!

2023-10-15 18:25 UTC, yodatak commented
I think i got an error too i cannot make any thumbernails if i have PREFER WIDE GAMUT enabled

2023-12-26 18:39 UTC, mertalev commented
I updated this branch to use the new sharp feature to set ICC profiles and rebased. Tested by right-clicking a preview image and confirming EXIF metadata is stripped and the ICC profile is set.

2023-12-26 21:13 UTC, jrasm91 approved these changes

2023-12-26 21:23 UTC, mertalev approved these changes

2023-12-26 21:27 UTC, merged