chore(docs): Added guide on remote access
immich-app/immich pull request #5350
Opened 2023-11-28 00:45 UTC by thariq-shanavas

A brief guide on different ways to access immich remotely. I use Wireguard to connect to my server - apologies for any technical mistakes in what I've written about reverse proxy. Let me know and I'll be happy to fix it!

2023-11-28 09:29 UTC, bo0tzz requested changes
This is pretty much exactly what I had in mind, thank you!

2023-11-28 09:29 UTC, bo0tzz commented on docs/docs/guides/remote-access.md
> +- Both the Immich web interface and API may be exposed to the internet. Immich is under very active developement and the existence of severe security vulnerabilities cannot be ruled out.
A self-signed cert is not technically a standalone remote access option, but would be a part of a remote proxy setup. I would suggest removing this section and instead adding a note to the reverse proxy section, indicating that with a remote proxy a certificate should be used for https. The options there are to get a free certificate via Let's Encrypt (preferred), or to use a self signed one.

2023-11-28 09:29 UTC, bo0tzz commented on docs/docs/guides/remote-access.md
> +A reverse proxy is a service that sits between web servers and clients. A reverse proxy increases security by hiding the server IP address, which makes targeted attacks like [DDoS](https://www.cloudf
A reverse proxy does not necessarily hide the server IP/make targeted attacks harder. This is only the case if you're using something like cloudflare, but not when you're running a reverse proxy like nginx on your server. Maybe cloudflare and a local proxy server should be separate sections?

2023-11-28 19:54 UTC, thariq-shanavas commented on docs/docs/guides/remote-access.md
> +A reverse proxy is a service that sits between web servers and clients. A reverse proxy increases security by hiding the server IP address, which makes targeted attacks like [DDoS](https://www.cloudf
Thank you, that clarifies some lingering confusion I had about reverse proxies. I made the changes.

2023-11-28 21:07 UTC, bo0tzz approved these changes

2023-11-28 21:20 UTC, jrasm91 commented
This looks pretty good. Any thoughts on making the pro's and con's list start with ✅ and ❌ or similar?

2023-11-29 00:49 UTC, merged

2023-11-29 05:17 UTC, thariq-shanavas commented
Thank you for the formatting fix! I was just about to get to it.