check if sidecarPath exists
immich-app/immich pull request #6293
Opened 2024-01-09 13:22 UTC by JW-CH

Fixes #6169

2024-01-09 13:23 UTC, JW-CH commented on server/src/domain/metadata/metadata.service.ts
> +          `Sidecar-File '${asset.sidecarPath}' for asset '${asset.id}' does not exist on the filesystem`,
Is an error/warning enough or does the db-field need to be nulled when not found?

2024-01-09 13:36 UTC, danieldietzler requested changes
What is the point of all this? `exiftool.read` should just throw an error (which we catch in the repository `readTags` method)

2024-01-09 13:36 UTC, danieldietzler commented on server/src/domain/metadata/metadata.service.ts
> +          `Sidecar-File '${asset.sidecarPath}' for asset '${asset.id}' does not exist on the filesystem`,
Don't import `fs` in domain/ files.

2024-01-09 18:41 UTC, jrasm91 submitted a review, later dismissed
It seems like this is something better suited for the sidecar sync/discover job. Sync can probably be updated to null out the database in the case the file no longer exists.

2024-01-10 16:57 UTC, JW-CH commented
TODO: Add valuable tests 🤣

2024-01-17 22:34 UTC, danieldietzler commented
Hey @JW-CH, just wanting to check in... Would you like us to add some tests or do you plan on adding them yourself?

2024-02-05 22:10 UTC, danieldietzler approved these changes

2024-02-07 17:28 UTC, jrasm91 approved these changes

2024-02-07 17:30 UTC, merged