fix(mobile): don't crop memories in landscape mode
immich-app/immich pull request #6907
Opened 2024-02-04 12:35 UTC by hrdl-github

Fix #6890

2024-02-17 11:48 UTC, martyfuhry requested changes

2024-02-17 11:48 UTC, martyfuhry commented on mobile/lib/modules/memories/ui/memory_card.dart
> -              BoxFit fit = BoxFit.fitWidth;
I think this is the only line you need to change. Box fit cover looks better for memories if ter aspect ratios are nearly close enough.

2024-02-17 13:49 UTC, martyfuhry commented on mobile/lib/modules/memories/ui/memory_card.dart
> -                    phoneAspectRatio * 1.25 > aspectRatio) {
Oh woops. This must have been because of the reversed aspect ratio bug I was experiencing when I made this. Feel free to fix it here!

2024-02-17 14:35 UTC, martyfuhry commented
LGTM! I'm not at my desk so I didn't test it, but this looks great!

2024-02-17 14:35 UTC, martyfuhry approved these changes

2024-02-23 16:54 UTC, shenlong-tanwen commented
@hrdl-github Can you re-base your changes over the latest main branch?

2024-02-23 17:05 UTC, merged