Fix external weights loading during runtime in OpenVINO EP
immich-app/immich pull request #7525
Opened 2024-02-29 10:48 UTC by agrawalsourav98

Some models that are large e.g. [ViT-H-14-378-quickgelu__dfn5b](https://huggingface.co/immich-app/ViT-H-14-378-quickgelu__dfn5b/tree/main/visual) and have their attributes split into multiple files are loaded at runtime instead of the entire model being loaded during session creation.

This PR attempts to fix that behaviour.

2024-02-29 18:34 UTC, mertalev requested changes
The concurrency issue aside, I also don't like that we're bolting on temporary code and adding overhead like this.

2024-02-29 18:34 UTC, mertalev commented on machine-learning/app/main.py
> +        os.chdir(cwd)
This doesn't make sense with multiple requests in flight.

2024-02-29 23:47 UTC, mertalev commented
FWIW I think it's possible to solve the external data not being loaded eagerly by calling `run` with dummy data after the session is created. That should force all the weights to be loaded. Still not ideal but it at least keeps the temporary code in one place.

2024-03-01 06:12 UTC, agrawalsourav98 commented
> FWIW I think it's possible to solve the external data not being loaded eagerly by calling `run` with dummy data after the session is created. That should force all the weights to be loaded. Still not ideal but it at least keeps the temporary code in one place.

Yeah, that is something we can do. I am not a fan of hacky stuff either it's just that I don't think intel cares enough that we would see newer packages anytime soon, so maybe we shouldn't rely on them.

I would try this out and update this PR if it is viable else let's just drop this approach.

2024-03-01 07:05 UTC, mertalev commented
I looked at their release cadence and they seem to like doing April releases. They probably scheduled it to be some time next month. Granted if we have a different issue with that release, it'll be half a year before they release the next one lol. I guess we can just see if this patch works and wait for April, then maybe look at building it ourselves if it comes to that.

2024-03-01 07:43 UTC, agrawalsourav98 commented
> I looked at their release cadence and they seem to like doing April releases. They probably scheduled it to be some time next month. Granted if we have a different issue with that release, it'll be half a year before they release the next one lol. I guess we can just see if this patch works and wait for April, then maybe look at building it ourselves if it comes to that.

Yes, I building can be a better option in the future. They provide a ready to use DockerFile for OpenVINO [here](https://github.com/microsoft/onnxruntime/blob/main/dockerfiles/Dockerfile.openvino), so I don't think we should be too worried about building it ourselves.

2024-03-19 15:50 UTC, agrawalsourav98 commented
Closing as it has been fixed by #7854 and #8018

2024-03-19 15:50 UTC, closed without merging