fix(server): delete thumbnail for readonly asset
immich-app/immich pull request #8593
Opened 2024-04-07 09:27 UTC by Ynng

Closes #4863 
Deletes thumbnail and other generated files for read-only assets

This is safe as only external library files use the "isReadOnly" boolean

2024-04-07 10:27 UTC, danieldietzler requested changes
The sidecar file isn't necessarily generated by immich.

2024-04-07 10:44 UTC, Ynng commented
I'm not familiar with sidecar files tbh.
What are some common ways people use them?

Is it safe to assume sidecar files of external assets are also external?

2024-04-07 11:45 UTC, jrasm91 reviewed
What is the value of from external when an asset is deleted here?

2024-04-07 22:59 UTC, Ynng commented
In `handleAssetDeletion`, for external assets, there's a guard clause making sure `fromExternal` is true.
In the test case the readonly asset is not external and `fromExternal` is false.

2024-04-08 00:22 UTC, jrasm91 approved these changes

2024-04-08 16:43 UTC, danieldietzler approved these changes

2024-04-08 16:54 UTC, merged

2024-04-23 23:27 UTC, malavolti commented
Dear @Ynng and @danieldietzler,

I'm using the latest version of Immich (1.102.3) and I currently have 18874 Untracked files:

![immich-untracked-files](https://gist.github.com/assets/3010502/7c34ce6d-e05c-4177-8092-4dc4df58d012)

from an external directory that I've removed in the past.

Can you help me to solve this issue, please?

Thank you so much!

2024-04-24 07:52 UTC, danieldietzler commented
@malavolti This is not something that should be discussed in a closed PR. Could you open a community Q&A post or hop onto our discord?