Update "move all data" instructions in FAQ
immich-app/immich pull request #8976
Opened 2024-04-20 20:14 UTC by aberndsen

chore(docs): update "move all data" FAQ instructions.

2024-04-20 20:16 UTC, bo0tzz approved these changes

2024-04-21 21:31 UTC, mmomjian requested changes
Thank you for your PR. Are you able to change to SQL-style comments? We would need to also edit the "reassign albums" and "reassign people" blocks, which are just above the lines changed in this PR

2024-04-21 21:31 UTC, mmomjian commented on docs/docs/FAQ.mdx
> +// (optionally) reassign external libraries
```suggestion
-- (optionally) reassign external libraries
```

2024-04-21 21:31 UTC, mmomjian commented on docs/docs/FAQ.mdx
>  // reassign assets
```suggestion
-- reassign assets
```

2024-04-22 12:27 UTC, aberndsen commented
Hi @mmomjian 

I've adjusted the "move all data" section to have sql-style comments throughout. I also "promoted" the optional changes to the **libraries** table, indicating there are four tables in total that should be changed if one wants to move all data to a different user.

2024-04-22 12:53 UTC, merged