fix install.sh add random password for .env
immich-app/immich pull request #9282
Opened 2024-05-06 13:29 UTC by xiagw

2024-05-06 13:38 UTC, mmomjian requested changes

2024-05-06 13:38 UTC, mmomjian commented on install.sh
> +  sed -i -e "s/DB_PASSWORD=postgres/DB_PASSWORD=${rand_pass}/" ./.env
Thanks. I like these changes. I would recommend adding some error handling here. We don’t know for sure if OpenSSL will be present on every system. Can we split the OpenSSL and head commands into 2 lines and then add a `|| return` for all 3 new commands?

2024-05-11 19:10 UTC, danieldietzler approved these changes

2024-05-11 19:42 UTC, mmomjian approved these changes

2024-05-13 01:05 UTC, zackpollard requested changes

2024-05-13 01:05 UTC, zackpollard commented on install.sh
> +  # rand_pass=$(openssl rand -base64 20 | tr -dc A-Za-z0-9 | head -c10)
I don't think we need to keep the other implementation commented here, lets just remove it if we're going with the other, more compatible implementation
```suggestion
```

2024-05-14 09:58 UTC, zackpollard approved these changes

2024-05-14 09:58 UTC, merged