Support special characters in library paths
immich-app/immich pull request #9385
Opened 2024-05-11 02:42 UTC by sushain97

Directories with special characters, like `(`, aren't properly crawled. This is fixed by escaping the provided paths before they're passed to `fast-glob`. My newly added test now passes. But, another test that uses `*` had to be deleted since we can't treat input paths as regular expressions and verbatim at the same time. I audited the use cases and it seems like only actual paths would be passed (please double check!). In particular, library paths are validated as real paths before being crawled.

If this behavior is intentional, the docs/UI should probably clarify that users need to escape special characters themselves. The path validation logic would also need to be tweaked to 'unescape' before checking the path. That seems a bit confusing.

2024-05-11 03:43 UTC, sushain97 commented on server/src/repositories/storage.repository.ts
> +    const base = escapedPaths.length === 1 ? escapedPaths[0] : `{${escapedPaths.join(',')}}`;
This code feels a bit redundant since `Array.join` should work fine on a singleton array. I just left it as is but can tweak.

2024-05-11 10:16 UTC, danieldietzler approved these changes

2024-05-12 00:00 UTC, sushain97 commented
@danieldietzler thanks for the review! would it be possible to get this merged before the next release?

2024-05-13 13:46 UTC, jrasm91 requested changes
I would prefer to just add a note to the docs explaining how to escape special characters, rather than removing the "glob-matching" feature altogether for _every_ user.

2024-05-13 18:26 UTC, sushain97 commented
@jrasm91 I don't think that feature really works since invalid paths are rejected: https://github.com/immich-app/immich/blob/540e568e9d29abbf4306c4ff761614bb5cc93291/server/src/services/library.service.ts#L315.

I'd argue the current behavior is a regression rather than a feature :) External libraries with `(` used to work and now all their assets are marked offline.

2024-05-13 19:23 UTC, jrasm91 approved these changes
Oh, I see. Maybe it does make more sense then for the import paths to just point to an existing folder (no glob syntax) and only the exclude paths use special characters (glob syntax).

2024-05-13 19:56 UTC, sushain97 commented
> Oh, I see. Maybe it does make more sense then for the import paths to just point to an existing folder (no glob syntax) and only the exclude paths use special characters (glob syntax).

That seems like reasonable behavior and this PR will preserve it since the exclusion patterns are still passed to `fast-glob` verbatim.

I could see a future feature that lets you use globs on an per path opt-in basis. Not sure it'd be a common ask, though.

2024-05-13 21:44 UTC, merged